on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,3,5'

name: publish_docker

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.repository }}/iseeu:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
