on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 5'

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.repository }}/iseeu:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
